# Разрешённые команды, которые можно использовать во время проверки
command:
  - /msg

# Сообщения, отображаемые во время проверки
messages:
  title_main: '&cВЫ НА ПРОВЕРКЕ' # Основной заголовок
  title_sub: '&eБудьте терпеливы и внимательны' # Подзаголовок
  toggle_on_checker: '&aВы поставили %target% на проверку' # Сообщение проверяющему при начале проверки
  toggle_on_target: '&cВы поставлены на проверку игроком %checker%' # Сообщение проверяемому при начале проверки
  toggle_off_checker: '&aВы сняли проверку с %target%' # Сообщение проверяющему при снятии проверки
  toggle_off_target: '&aПроверка с вас снята игроком %checker%' # Сообщение проверяемому при снятии проверки
  no_permission: '&cУ вас нет прав для использования этой команды' # Сообщение при отсутствии прав
  player_not_found: '&cИгрок не найден' # Сообщение при отсутствии игрока

# Длительность проверки в секундах
check_duration_seconds: 180

# Тип блока для платформы под игроком во время проверки
platform_block: STONE

# Включить или отключить установку платформы под игроком
platform_enabled: true

# Координаты для телепортации проверяемого (если используется -a)
checkLocation:
  world: world
  x: -22.640432104331424
  y: 31.0
  z: 155.42215866032697
  yaw: -303.65344
  pitch: 13.640387

# Действия при таймауте проверки и при выходе игрока во время проверки
actions:
  on_timeout: "/ban %user% 30d игнор проверки"
  on_quit: "/ban %user% 30d лив с проверки"